service:
  name: sls-kanban

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  documentation:
    api:
      info:
        version: v1.0.0
        title: ${self:service.name}
        description: Serverless kanban-card application

  serverless-offline:
    port: 3003

  dynamodb:
    #  DynamoDB Local for some stages
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment if  DynamoDB runs locally
    # noStart: true

  s3:
    host: localhost
    port: 8200
    directory: /tmp
    noStart: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

  tracing:
    lambda: true
    apiGateway: true

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    KANBAN_CARD_TABLE: kanbancard-${self:provider.stage}
    KANBAN_CARD_TABLE_IDX: kanbancard-idx-${self:provider.environment.KANBAN_CARD_TABLE}
    ATTACHMENTS_S3_BUCKET: serverless-kanban-card-attachments-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    JWKS_URL: 'https://dev-eq7g28uo.us.auth0.com/.well-known/jwks.json'
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR

  iamRoleStatements:
    - Effect: Allow
      Action:
        - codedeploy:*
      Resource:
        - '*'

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - '*'

  GetKanbanCard:
    handler: src/lambda/http/getKanbanCards.handler
    events:
      - http:
          authorizer: Auth
          cors: true
          method: get
          path: kanbancards

    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.KANBAN_CARD_TABLE}/index/${self:provider.environment.KANBAN_CARD_TABLE_IDX}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - '*'

  CreateKanbanCard:
    handler: src/lambda/http/createKanbanCard.handler
    events:
      - http:
          authorizer: Auth
          cors: true
          method: post
          path: kanbancards
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new entry to the kanbancard.
            description: Create a new entry to the kanbancard.

    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.KANBAN_CARD_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - '*'

  UpdateKanbanCard:
    handler: src/lambda/http/updateKanbanCard.handler
    events:
      - http:
          authorizer: Auth
          cors: true
          method: patch
          path: kanbancards/{kanbanCardId}
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Update a kanbancard entry
            description: Update a kanbancard entry

    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.KANBAN_CARD_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - '*'

  DeleteKanbanCard:
    handler: src/lambda/http/deleteKanbanCard.handler
    events:
      - http:
          authorizer: Auth
          cors: true
          method: delete
          path: kanbancards/{kanbanCardId}
          documentation:
            summary: Delete a kanbancard entry.
            description: Delete a kanbancard entry.

    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.KANBAN_CARD_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - '*'

  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          authorizer: Auth
          cors: true
          method: post
          path: kanbancards/{kanbanCardId}/attachment

    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_S3_BUCKET}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - '*'

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    KanbanCardDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: kanbanCardId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: kanbanCardId
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.KANBAN_CARD_TABLE_IDX}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: kanbanCardId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.KANBAN_CARD_TABLE}

    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ATTACHMENTS_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_S3_BUCKET}/*
        Bucket:
          Ref: AttachmentsBucket
